### ISSUE TITLE
how the depth map is obtained？

### ISSUE THREAD

**Issue by yuancaimaiyi** [tsattler/meshloc_release#1]
@tsattler @v-pnk 
Hi,Seeing that the code is essentially based on the relocation of the depth map, I am very confused by how the depth map is obtained?Suppose that even if the lidar back-projection image obtains the depth map, the depth map is sparse or has holes. It is difficult to ensure that the matched feature points have depth. So I want to know how to get the depth map and whether to use the algorithm of depth map completion?
                                                                                                                                                                                Thanks

**Comment by tsattler** [comment]
Hi, thanks for your interest in the project and your question. We are rendering meshes to obtain depth maps (hence the name meshloc). As a result, we are avoiding the sparsity problem. The code will still work with sparse depth maps though (as long as enough features have a valid depth measurement).

You can read more details on the method in the arXiv version of the paper, which should be out on Monday.

**Comment by tsattler** [comment]
The arXiv paper is available here: https://arxiv.org/abs/2207.10762

**Comment by yuancaimaiyi** [comment]
@tsattler  awesome, thank you very much！
