### ISSUE TITLE
undefined symbol: __pow_finite while importing meshloc

### ISSUE THREAD

**Issue by weient** [tsattler/meshloc_release#10]
@tsattler 
Hi, thank you for the great work! I've come across an issue while importing meshloc in localize.py. There is no error while building meshloc from this repo, but an error occurs when running localize.py:
`Traceback (most recent call last):
  File "localize.py", line 48, in <module>
    import meshloc
ImportError: /home/weientai18/meshloc_release/meshloc.cpython-38-x86_64-linux-gnu.so: undefined symbol: __pow_finite`
I wonder if you have encountered similar issues before?
Here are some outputs when running `python setup.py develop`:

> running develop
/home/weientai18/anaconda3/envs/immatch1/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!
        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.
        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************
!!
  easy_install.initialize_options(self)
/home/weientai18/anaconda3/envs/immatch1/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!
        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.
        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************
!!
  self.initialize_options()
running egg_info
writing meshloc.egg-info/PKG-INFO
writing dependency_links to meshloc.egg-info/dependency_links.txt
writing top-level names to meshloc.egg-info/top_level.txt
reading manifest file 'meshloc.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'meshloc.egg-info/SOURCES.txt'
running build_ext
['cmake', '/home/weientai18/meshloc_release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/weientai18/meshloc_release', '-DPYTHON_EXECUTABLE=/home/weientai18/anaconda3/envs/immatch1/bin/python', '-DCMAKE_BUILD_TYPE=Release']
-- pybind11 v2.11.0 dev1
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found required Ceres dependency: Eigen version 3.4.0 in /home/weientai18/anaconda3/envs/immatch1/share/eigen3/cmake
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /home/weientai18/anaconda3/envs/immatch1 with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found required Ceres dependency: Eigen version 3.4.0 in /home/weientai18/anaconda3/envs/immatch1/share/eigen3/cmake
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /home/weientai18/anaconda3/envs/immatch1 with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Found Boost: /home/weientai18/anaconda3/envs/immatch1/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: program_options filesystem system unit_test_framework 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FLANN
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found SQLite3
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found Boost: /home/weientai18/anaconda3/envs/immatch1/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.48")  
-- Boost include dirs: /home/weientai18/anaconda3/envs/immatch1/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Configuring done
-- Generating done
-- Build files have been written to: /home/weientai18/meshloc_release/build/temp.linux-x86_64-cpython-38
Consolidate compiler generated dependencies of target meshloc
[100%] Built target meshloc
Creating /home/weientai18/anaconda3/envs/immatch1/lib/python3.8/site-packages/meshloc.egg-link (link to .)
meshloc 0.1.0 is already the active version in easy-install.pth
Installed /home/weientai18/meshloc_release
Processing dependencies for meshloc==0.1.0
Finished processing dependencies for meshloc==0.1.0

**Comment by tsattler** [comment]
I am sorry, I never encountered this issue before.

**Comment by v-pnk** [comment]
Hi @weient !
Sorry, I also did not encounter this error before. From a quick search, it looks like an issue with the version of glibc.

**Comment by weient** [comment]
@v-pnk @tsattler thank you for your reply! I'll try build Meshloc again with different version of glibc.
