### ISSUE TITLE
Question about how to generate the mesh about aachen?

### ISSUE THREAD

**Issue by Gatsby23** [tsattler/meshloc_release#2]

**Comment by tsattler** [comment]
Please have a look at the paper corresponding to this repository (https://arxiv.org/pdf/2207.10762.pdf). The meshes are available here: https://data.ciirc.cvut.cz/public/projects/2022MeshLoc/aachen_day_night_v11/meshes/

**Comment by Gatsby23** [comment]
> Please have a look at the paper corresponding to this repository (https://arxiv.org/pdf/2207.10762.pdf). The meshes are available here: https://data.ciirc.cvut.cz/public/projects/2022MeshLoc/aachen_day_night_v11/meshes/

Sorry for bothering you again: when I run the undistort the images. It shows boost::filesystem_error:
```
It shows No such file or directory: "~/Dataset/dense/images/sequences/nexus4_sequences/sequence_1"。
```
Have you met the same Problem？What version of colmap have you used?

**Comment by tsattler** [comment]
Any recent version of Colmap should work. I either used 3.6 or 3.7. 

Are you sure you have downloaded all necessary images for the Aachen dataset?

**Comment by Gatsby23** [comment]
> Any recent version of Colmap should work. I either used 3.6 or 3.7.
> 
> Are you sure you have downloaded all necessary images for the Aachen dataset?

Yes, by the way, what is the memory about your computer？

**Comment by tsattler** [comment]
I used a PC with 64 GB RAM to create the models.

**Comment by Gatsby23** [comment]
> I used a PC with 64 GB RAM to create the models.

When I use the colmap GUI to do the stereo fusion to get the ply. It always get killed. Have you met this problem?

**Comment by tsattler** [comment]
You are likely running out of memory. There are some tips on how to handle limited resources in the Colmap documentation and the Colmap faq.

**Comment by Gatsby23** [comment]
> You are likely running out of memory. There are some tips on how to handle limited resources in the Colmap documentation and the Colmap faq.

Yes I have noticed that, have you downscale the image size to do the reconstruction？ My computer is 128 memory. But it still met the problem.

**Comment by tsattler** [comment]
I think I have created multiple meshes, both at lower resolution and at a maximum side length of 1600. For the fusion step, I typically limit the amount of memory Colmap can use.

**Comment by Gatsby23** [comment]
> I think I have created multiple meshes, both at lower resolution and at a maximum side length of 1600. For the fusion step, I typically limit the amount of memory Colmap can use.

Sorry for bothering you again. I'm a freshman to the colmap. How to limit the colmap use at all？ The only thing I can find is to downscale the cache( from the tip at here: https://github.com/colmap/colmap/issues/732). I don't want to downscale the image resolution at all. Could you please give me some tips about that？

**Comment by tsattler** [comment]
Yes, I meant reducing the cache size.

**Comment by Gatsby23** [comment]
> Yes, I meant reducing the cache size.

I download to the 16 cache, but it crashes at last. Could you please share your cache size？

**Comment by tsattler** [comment]
I think cache sizes of 16, 24, and 32 GB have worked for me. I don't think I used a smaller cache size for the Aachen model (but it is also some time ago and I don't remember).

**Comment by Gatsby23** [comment]
> I think cache sizes of 16, 24, and 32 GB have worked for me. I don't think I used a smaller cache size for the Aachen model (but it is also some time ago and I don't remember).

I use the 16, but the memory size is still increasing until it's crashed.
