### ISSUE TITLE
I read the paper mentioning Position averaging, but found nothing about it in the code?

### ISSUE THREAD

**Issue by coder12333444** [tsattler/meshloc_release#3]
@v-pnk @tsattler 
Hi,I'm confused about the underlined part, since C_i_ is a sampling point based on C (virtual), how do I go about counting the number of inliers points in 2d-3D？
![image](https://user-images.githubusercontent.com/87088407/182064820-068c6cea-46a3-4f6b-9688-f4e482c54c8f.png)

**Comment by tsattler** [comment]
Each C_i, together with the rotation matrix R, defines a pose. For this pose, we count the number of 2D-3D matches (created in a previous step) that are inliers to this pose by projecting the 3D points into the images and measuring the reprojection error compared to the corresponding 2D coordinates.

The corresponding part of the code is this: https://github.com/tsattler/meshloc_release/blob/main/src/pose_estimation.cc#L640-L673
