### ISSUE TITLE
NetVLAD Image Retrieval Code Part

### ISSUE THREAD

**Issue by alexs7** [tsattler/meshloc_release#4]
Hello,

I was just wondering do you plan to release the netvlad-based code part that was used for image retrieval ?

Thanks!

**Comment by tsattler** [comment]
For the paper, we did not perform retrieval ourselves but used the retrieval results already used by hloc (https://github.com/cvg/Hierarchical-Localization/blob/master/pairs/aachen_v1.1/pairs-query-netvlad50.txt). Thus, there is no code to release.

**Comment by alexs7** [comment]
Ok Thanks!
