### ISSUE TITLE
How to render a large-scale scene in real-time?

### ISSUE THREAD

**Issue by rann1018** [tsattler/meshloc_release#5]
Hi Tsattler,

Thanks for your good work. I notice you mention that large 3D models can be rendered in less than a millisecond in paper.
However, when I used pyrender and pytorch3d to render a large-scale scene, it usually took several seconds or longer.
Would you please tell me what tool do you use to render such a large-scale scene?

Looking forward to your reply.

**Comment by tsattler** [comment]
We are using code that was released by this paper: https://arxiv.org/pdf/1601.06950.pdf
But it seems their code is not available anymore.

They had implemented an OpenGL pipeline in C++, which should be considerably faster than having a pipeline wrapped in Python.
