### ISSUE TITLE
How to run MeshLoc on own data

### ISSUE THREAD

**Issue by zwl995** [tsattler/meshloc_release#6]
Hi，tsattler
The content of your research is exciting.
How to run MeshLoc on own data?

**Comment by tsattler** [comment]
Hi @zwl995 ,

Thank you very much for your kind words.

To run MeshLoc on your own dataset, you will need to provide the camera poses and intrinsics of the database images in Colmap's data format. In addition, you will need to render depth maps from the poses and intrinsics of the database images in a format that can be loaded by the code (see the code). Please note that we are not handling distorted database images, so you will need to undistort the database images before rendering and provide the intrinsics of the undistorted images.

**Comment by zwl995** [comment]
Thank you very much for your answer, I will try it out and keep following your work, looking forward to your update.
