### ISSUE TITLE
The accuracy of the final acquired pose of MeshLoc

### ISSUE THREAD

**Issue by LSK0821** [tsattler/meshloc_release#8]
Hello, dear author! This work is very wonderful.
I tried to experiment with the pose of some images in the 12scens_kitchen file.
I found that the final meshloc obtained quaternions are basically the same as the true value (but the first W appears negative， XYZ is similar). 
However, the position difference is large.
I tried to use d2net and LOFTER, and the final result is similar, with a big position gap. 
Here is my parameter configuration,

![image](https://github.com/tsattler/meshloc_release/assets/69196380/8f7eb816-6d4c-4c5a-bffd-9e23423449c4)
![image](https://github.com/tsattler/meshloc_release/assets/69196380/c47d610e-88f4-4dae-9f7f-98c9c66cc3ae)
![image](https://github.com/tsattler/meshloc_release/assets/69196380/074fd1ff-cc9a-4ea6-932c-c06ec1f3dbfc)
![image](https://github.com/tsattler/meshloc_release/assets/69196380/afeacc18-5603-4153-934f-10adf45f45d9)

 what is wrong ?

Here are the quaternions obtained from the rotation matrix of pose.txt of frame-000000-colar.jpg
![image](https://github.com/tsattler/meshloc_release/assets/69196380/654f3ba8-92cc-451d-a619-0ee892bc63b6)

**Comment by tsattler** [comment]
You are comparing poses that cannot be directly compared.

MeshLoc returns the camera pose as `R`, `t`, such that a 3D point `p_w` in world coordinates is mapped to a point `p_c` in camera coordinates as `p_c = R * p_w + t`. 

The pose files provided by the 12 Scenes dataset store the pose as `R^T`, `c`, where `c = -R^T * t` is the camera position in world coordinates.
