### ISSUE TITLE
Unable to achieve accuracy shown in Benchmark

### ISSUE THREAD

**Issue by NudtCalculus** [tsattler/meshloc_release#9]
Hi tsattler,  The results obtained by using parameters given in README (match method is LoFTR) can not achieve the accuracy shown in the benchmark, especially at (0.25m, 2 degrees) level. Would you please help us solve it?
Looking forward to your reply.
![ebfdffbab76cf71f97ac168343dec6f3](https://github.com/tsattler/meshloc_release/assets/57952398/0b76d269-91f7-442e-8789-4024927864ef)

**Comment by tsattler** [comment]
Can you explain what exactly you are doing?

**Comment by NudtCalculus** [comment]
We are running meshloc on the Aachen Day-Night v1.1 dataset using parameters given in README, but the result is not so precise.

**Comment by v-pnk** [comment]
Hi @NudtCalculus ,
Are you trying to match the highlighted results in the Table 3 in the paper?

![image](https://github.com/tsattler/meshloc_release/assets/44996094/65868c47-fd85-49f2-9ed9-fb035d30f16e)

That is:
- database of original photos (not rendered) from Aachen v1.1 dataset at 800 px resolution
- depth maps rendered from AC14 mesh
- LoFTR with none of "triangulate", "merge_3D_points", "cluster_keypoints", "covisibility_filtering", "all_matches_ransac" adjustments turned on
- precomputed retrieval pairs with NetVLAD top 50 database images
- RANSAC with min. 10,000 and max. 100,000 iterations and 20 px reprojection error threshold

**Comment by NudtCalculus** [comment]
Thanks for your reply, I'll try again.
